const fs=require('node:fs'), vm=require('node:vm'), assert=require('node:assert/strict');
const patch=fs.readFileSync(__dirname+'/../patches/flowsense/0003-cpu-availability.patch','utf8');
const added=patch.split('\n').filter(l=>l.startsWith('+')&&!l.startsWith('+++')).map(l=>l.slice(1));
const source=added.filter(l=>l.includes('var cpu')).join('\n');
const check=vm.runInNewContext('(function(bypass){'+source+';return {available:cpuAvailable,pct:cpuPct};})');
assert.equal(check({}).available,false);
assert.equal(check({cpu_pct:null}).available,false);
assert.equal(check({cpu_pct:0,cpu_available:false}).available,false);
assert.equal(check({cpu_pct:0,cpu_available:true}).available,true);
assert.equal(check({cpu_pct:37,cpu_available:true}).pct,37);
assert.equal(check({cpu_pct:NaN}).available,false);
console.log('CPU absence is distinct from a valid idle sample.');
